package org.saxt.cms.model;
// Generated Mar 3, 2018 2:20:56 PM by Hibernate Tools 3.6.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Component generated by hbm2java
 */
@Entity
@Table(name = "component", catalog = "cms")
public class Component implements java.io.Serializable {

	private Long id;
	private String name;
	private String description;
	private Date creationDate;
	private String html;
	private String previewHtml;
	private String type;
	private String componentFields;
	private String guiHtml;
	private Set<PageComponent> pageComponents = new HashSet<PageComponent>(0);

	public Component() {
	}

	public Component(String html, String previewHtml, String type) {
		this.html = html;
		this.previewHtml = previewHtml;
		this.type = type;
	}

	public Component(String name, String description, Date creationDate, String html, String previewHtml, String type,
			String componentFields, String guiHtml, Set<PageComponent> pageComponents) {
		this.name = name;
		this.description = description;
		this.creationDate = creationDate;
		this.html = html;
		this.previewHtml = previewHtml;
		this.type = type;
		this.componentFields = componentFields;
		this.guiHtml = guiHtml;
		this.pageComponents = pageComponents;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", length = 19)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "html", nullable = false, length = 65535)
	public String getHtml() {
		return this.html;
	}

	public void setHtml(String html) {
		this.html = html;
	}

	@Column(name = "preview_html", nullable = false, length = 65535)
	public String getPreviewHtml() {
		return this.previewHtml;
	}

	public void setPreviewHtml(String previewHtml) {
		this.previewHtml = previewHtml;
	}

	@Column(name = "type", nullable = false, length = 12)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "component_fields", length = 65535)
	public String getComponentFields() {
		return this.componentFields;
	}

	public void setComponentFields(String componentFields) {
		this.componentFields = componentFields;
	}

	@Column(name = "gui_html", length = 65535)
	public String getGuiHtml() {
		return this.guiHtml;
	}

	public void setGuiHtml(String guiHtml) {
		this.guiHtml = guiHtml;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "component")
	public Set<PageComponent> getPageComponents() {
		return this.pageComponents;
	}

	public void setPageComponents(Set<PageComponent> pageComponents) {
		this.pageComponents = pageComponents;
	}

}
