package org.saxt.cms.model;
// Generated Mar 3, 2018 2:20:56 PM by Hibernate Tools 3.6.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ContentProvider generated by hbm2java
 */
@Entity
@Table(name = "content_provider", catalog = "cms")
public class ContentProvider implements java.io.Serializable {

	private Long id;
	private String name;
	private String description;
	private String timMerchantId;
	private String windUsername;
	private String windPassword;
	private String h3gUsername;
	private String h3gPassword;
	private String status;
	private Date creationDate;
	private Date lastModifiedDate;
	private Set<User> users = new HashSet<User>(0);
	private Set<Service> services = new HashSet<Service>(0);

	public ContentProvider() {
	}

	public ContentProvider(String name, String status, Date creationDate, Date lastModifiedDate) {
		this.name = name;
		this.status = status;
		this.creationDate = creationDate;
		this.lastModifiedDate = lastModifiedDate;
	}

	public ContentProvider(String name, String description, String timMerchantId, String windUsername,
			String windPassword, String h3gUsername, String h3gPassword, String status, Date creationDate,
			Date lastModifiedDate, Set<User> users, Set<Service> services) {
		this.name = name;
		this.description = description;
		this.timMerchantId = timMerchantId;
		this.windUsername = windUsername;
		this.windPassword = windPassword;
		this.h3gUsername = h3gUsername;
		this.h3gPassword = h3gPassword;
		this.status = status;
		this.creationDate = creationDate;
		this.lastModifiedDate = lastModifiedDate;
		this.users = users;
		this.services = services;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "tim_merchant_id", length = 50)
	public String getTimMerchantId() {
		return this.timMerchantId;
	}

	public void setTimMerchantId(String timMerchantId) {
		this.timMerchantId = timMerchantId;
	}

	@Column(name = "wind_username", length = 50)
	public String getWindUsername() {
		return this.windUsername;
	}

	public void setWindUsername(String windUsername) {
		this.windUsername = windUsername;
	}

	@Column(name = "wind_password", length = 50)
	public String getWindPassword() {
		return this.windPassword;
	}

	public void setWindPassword(String windPassword) {
		this.windPassword = windPassword;
	}

	@Column(name = "h3g_username", length = 50)
	public String getH3gUsername() {
		return this.h3gUsername;
	}

	public void setH3gUsername(String h3gUsername) {
		this.h3gUsername = h3gUsername;
	}

	@Column(name = "h3g_password", length = 50)
	public String getH3gPassword() {
		return this.h3gPassword;
	}

	public void setH3gPassword(String h3gPassword) {
		this.h3gPassword = h3gPassword;
	}

	@Column(name = "status", nullable = false, length = 8)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", nullable = false, length = 19)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_modified_date", nullable = false, length = 19)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contentProvider")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contentProvider")
	public Set<Service> getServices() {
		return this.services;
	}

	public void setServices(Set<Service> services) {
		this.services = services;
	}

}
