package org.saxt.cms.model;
// Generated Mar 3, 2018 2:20:56 PM by Hibernate Tools 3.6.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ItemPageComponent generated by hbm2java
 */
@Entity
@Table(name = "item_page_component", catalog = "cms")
public class ItemPageComponent implements java.io.Serializable {

	private Long id;
	private Item item;
	private PageComponent pageComponent;
	private Date creationDate;
	private Date lastModifiedDate;

	public ItemPageComponent() {
	}

	public ItemPageComponent(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public ItemPageComponent(Item item, PageComponent pageComponent, Date creationDate, Date lastModifiedDate) {
		this.item = item;
		this.pageComponent = pageComponent;
		this.creationDate = creationDate;
		this.lastModifiedDate = lastModifiedDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "item_id")
	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "page_component_id")
	public PageComponent getPageComponent() {
		return this.pageComponent;
	}

	public void setPageComponent(PageComponent pageComponent) {
		this.pageComponent = pageComponent;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", length = 19)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_modified_date", nullable = false, length = 19)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

}
