package org.saxt.cms.model;
// Generated Mar 3, 2018 2:20:56 PM by Hibernate Tools 3.6.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PageComponent generated by hbm2java
 */
@Entity
@Table(name = "page_component", catalog = "cms")
public class PageComponent implements java.io.Serializable {

	private Long id;
	private Component component;
	private Page page;
	private Integer position;
	private Integer rowSize;
	private Integer pageSize;
	private Integer detail;
	private Integer error;
	private Integer purchase;
	private String searchField;
	private String orderBy;
	private String orderType;
	private String stagingJson;
	private String productionJson;
	private Date creationDate;
	private Date lastModifiedDate;
	private Set<ItemPageComponent> itemPageComponents = new HashSet<ItemPageComponent>(0);

	public PageComponent() {
	}

	public PageComponent(Date creationDate, Date lastModifiedDate) {
		this.creationDate = creationDate;
		this.lastModifiedDate = lastModifiedDate;
	}

	public PageComponent(Component component, Page page, Integer position, Integer rowSize, Integer pageSize,
			Integer detail, Integer error, Integer purchase, String searchField, String orderBy, String orderType,
			String stagingJson, String productionJson, Date creationDate, Date lastModifiedDate,
			Set<ItemPageComponent> itemPageComponents) {
		this.component = component;
		this.page = page;
		this.position = position;
		this.rowSize = rowSize;
		this.pageSize = pageSize;
		this.detail = detail;
		this.error = error;
		this.purchase = purchase;
		this.searchField = searchField;
		this.orderBy = orderBy;
		this.orderType = orderType;
		this.stagingJson = stagingJson;
		this.productionJson = productionJson;
		this.creationDate = creationDate;
		this.lastModifiedDate = lastModifiedDate;
		this.itemPageComponents = itemPageComponents;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "component_id")
	public Component getComponent() {
		return this.component;
	}

	public void setComponent(Component component) {
		this.component = component;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "page_id")
	public Page getPage() {
		return this.page;
	}

	public void setPage(Page page) {
		this.page = page;
	}

	@Column(name = "position")
	public Integer getPosition() {
		return this.position;
	}

	public void setPosition(Integer position) {
		this.position = position;
	}

	@Column(name = "row_size")
	public Integer getRowSize() {
		return this.rowSize;
	}

	public void setRowSize(Integer rowSize) {
		this.rowSize = rowSize;
	}

	@Column(name = "page_size")
	public Integer getPageSize() {
		return this.pageSize;
	}

	public void setPageSize(Integer pageSize) {
		this.pageSize = pageSize;
	}

	@Column(name = "detail")
	public Integer getDetail() {
		return this.detail;
	}

	public void setDetail(Integer detail) {
		this.detail = detail;
	}

	@Column(name = "error")
	public Integer getError() {
		return this.error;
	}

	public void setError(Integer error) {
		this.error = error;
	}

	@Column(name = "purchase")
	public Integer getPurchase() {
		return this.purchase;
	}

	public void setPurchase(Integer purchase) {
		this.purchase = purchase;
	}

	@Column(name = "search_field", length = 50)
	public String getSearchField() {
		return this.searchField;
	}

	public void setSearchField(String searchField) {
		this.searchField = searchField;
	}

	@Column(name = "order_by", length = 50)
	public String getOrderBy() {
		return this.orderBy;
	}

	public void setOrderBy(String orderBy) {
		this.orderBy = orderBy;
	}

	@Column(name = "order_type", length = 50)
	public String getOrderType() {
		return this.orderType;
	}

	public void setOrderType(String orderType) {
		this.orderType = orderType;
	}

	@Column(name = "staging_json", length = 65535)
	public String getStagingJson() {
		return this.stagingJson;
	}

	public void setStagingJson(String stagingJson) {
		this.stagingJson = stagingJson;
	}

	@Column(name = "production_json", length = 65535)
	public String getProductionJson() {
		return this.productionJson;
	}

	public void setProductionJson(String productionJson) {
		this.productionJson = productionJson;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", nullable = false, length = 19)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_modified_date", nullable = false, length = 19)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pageComponent")
	public Set<ItemPageComponent> getItemPageComponents() {
		return this.itemPageComponents;
	}

	public void setItemPageComponents(Set<ItemPageComponent> itemPageComponents) {
		this.itemPageComponents = itemPageComponents;
	}

}
