package org.saxt.cms.model;
// Generated Mar 3, 2018 2:20:56 PM by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Profile generated by hbm2java
 */
@Entity
@Table(name = "profile", catalog = "cms")
public class Profile implements java.io.Serializable {

	private Integer id;
	private String profileName;
	private String description;
	private String homeAction;
	private Set<Permission> permissions = new HashSet<Permission>(0);
	private Set<User> users = new HashSet<User>(0);

	public Profile() {
	}

	public Profile(String profileName, String description) {
		this.profileName = profileName;
		this.description = description;
	}

	public Profile(String profileName, String description, String homeAction, Set<Permission> permissions,
			Set<User> users) {
		this.profileName = profileName;
		this.description = description;
		this.homeAction = homeAction;
		this.permissions = permissions;
		this.users = users;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "profile_name", nullable = false, length = 50)
	public String getProfileName() {
		return this.profileName;
	}

	public void setProfileName(String profileName) {
		this.profileName = profileName;
	}

	@Column(name = "description", nullable = false, length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "home_action", length = 50)
	public String getHomeAction() {
		return this.homeAction;
	}

	public void setHomeAction(String homeAction) {
		this.homeAction = homeAction;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "profile_permission", catalog = "cms", joinColumns = {
			@JoinColumn(name = "profile_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "permission_id", nullable = false, updatable = false) })
	public Set<Permission> getPermissions() {
		return this.permissions;
	}

	public void setPermissions(Set<Permission> permissions) {
		this.permissions = permissions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "profile")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
