package org.saxt.cms.model;
// Generated Mar 3, 2018 2:20:56 PM by Hibernate Tools 3.6.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Service generated by hbm2java
 */
@Entity
@Table(name = "service", catalog = "cms")
public class Service implements java.io.Serializable {

	private Long id;
	private ContentProvider contentProvider;
	private String name;
	private String description;
	private String operator;
	private String timServiceUrl;
	private String h3gServiceUrl;
	private String windServiceUrl;
	private String postbackUrl;
	private String timProductId;
	private String h3gServiceId;
	private Byte noCreditsWeek;
	private String status;
	private Date creationDate;
	private Date lastModifiedDate;
	private Set<Page> pages = new HashSet<Page>(0);

	public Service() {
	}

	public Service(String name, String description, String status, Date creationDate, Date lastModifiedDate) {
		this.name = name;
		this.description = description;
		this.status = status;
		this.creationDate = creationDate;
		this.lastModifiedDate = lastModifiedDate;
	}

	public Service(ContentProvider contentProvider, String name, String description, String operator,
			String timServiceUrl, String h3gServiceUrl, String windServiceUrl, String postbackUrl, String timProductId,
			String h3gServiceId, Byte noCreditsWeek, String status, Date creationDate, Date lastModifiedDate,
			Set<Page> pages) {
		this.contentProvider = contentProvider;
		this.name = name;
		this.description = description;
		this.operator = operator;
		this.timServiceUrl = timServiceUrl;
		this.h3gServiceUrl = h3gServiceUrl;
		this.windServiceUrl = windServiceUrl;
		this.postbackUrl = postbackUrl;
		this.timProductId = timProductId;
		this.h3gServiceId = h3gServiceId;
		this.noCreditsWeek = noCreditsWeek;
		this.status = status;
		this.creationDate = creationDate;
		this.lastModifiedDate = lastModifiedDate;
		this.pages = pages;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "content_provider_id")
	public ContentProvider getContentProvider() {
		return this.contentProvider;
	}

	public void setContentProvider(ContentProvider contentProvider) {
		this.contentProvider = contentProvider;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", nullable = false, length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "operator", length = 50)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Column(name = "tim_service_url", length = 50)
	public String getTimServiceUrl() {
		return this.timServiceUrl;
	}

	public void setTimServiceUrl(String timServiceUrl) {
		this.timServiceUrl = timServiceUrl;
	}

	@Column(name = "h3g_service_url", length = 50)
	public String getH3gServiceUrl() {
		return this.h3gServiceUrl;
	}

	public void setH3gServiceUrl(String h3gServiceUrl) {
		this.h3gServiceUrl = h3gServiceUrl;
	}

	@Column(name = "wind_service_url", length = 50)
	public String getWindServiceUrl() {
		return this.windServiceUrl;
	}

	public void setWindServiceUrl(String windServiceUrl) {
		this.windServiceUrl = windServiceUrl;
	}

	@Column(name = "postback_url", length = 50)
	public String getPostbackUrl() {
		return this.postbackUrl;
	}

	public void setPostbackUrl(String postbackUrl) {
		this.postbackUrl = postbackUrl;
	}

	@Column(name = "tim_product_id", length = 50)
	public String getTimProductId() {
		return this.timProductId;
	}

	public void setTimProductId(String timProductId) {
		this.timProductId = timProductId;
	}

	@Column(name = "h3g_service_id", length = 50)
	public String getH3gServiceId() {
		return this.h3gServiceId;
	}

	public void setH3gServiceId(String h3gServiceId) {
		this.h3gServiceId = h3gServiceId;
	}

	@Column(name = "no_credits_week")
	public Byte getNoCreditsWeek() {
		return this.noCreditsWeek;
	}

	public void setNoCreditsWeek(Byte noCreditsWeek) {
		this.noCreditsWeek = noCreditsWeek;
	}

	@Column(name = "status", nullable = false, length = 8)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", nullable = false, length = 19)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_modified_date", nullable = false, length = 19)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "service")
	public Set<Page> getPages() {
		return this.pages;
	}

	public void setPages(Set<Page> pages) {
		this.pages = pages;
	}

}
