package org.saxt.cms.model;
// Generated Mar 3, 2018 2:20:56 PM by Hibernate Tools 3.6.0.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Subscription generated by hbm2java
 */
@Entity
@Table(name = "subscription", catalog = "cms")
public class Subscription implements java.io.Serializable {

	private SubscriptionId id;
	private String status;
	private String operator;
	private Date creationDate;
	private Date lastModifiedDate;
	private Date lastSubscriptionDate;
	private Date lastDeactivationDate;
	private Date lastBillingDate;
	private Date lastRenewalDate;
	private Integer retryNumber;

	public Subscription() {
	}

	public Subscription(SubscriptionId id, Date creationDate, Date lastModifiedDate) {
		this.id = id;
		this.creationDate = creationDate;
		this.lastModifiedDate = lastModifiedDate;
	}

	public Subscription(SubscriptionId id, String status, String operator, Date creationDate, Date lastModifiedDate,
			Date lastSubscriptionDate, Date lastDeactivationDate, Date lastBillingDate, Date lastRenewalDate,
			Integer retryNumber) {
		this.id = id;
		this.status = status;
		this.operator = operator;
		this.creationDate = creationDate;
		this.lastModifiedDate = lastModifiedDate;
		this.lastSubscriptionDate = lastSubscriptionDate;
		this.lastDeactivationDate = lastDeactivationDate;
		this.lastBillingDate = lastBillingDate;
		this.lastRenewalDate = lastRenewalDate;
		this.retryNumber = retryNumber;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "serviceId", column = @Column(name = "service_id", nullable = false, length = 50)),
			@AttributeOverride(name = "msisdn", column = @Column(name = "msisdn", nullable = false, length = 50)) })
	public SubscriptionId getId() {
		return this.id;
	}

	public void setId(SubscriptionId id) {
		this.id = id;
	}

	@Column(name = "status", length = 8)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "operator", length = 9)
	public String getOperator() {
		return this.operator;
	}

	public void setOperator(String operator) {
		this.operator = operator;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", nullable = false, length = 19)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_modified_date", nullable = false, length = 19)
	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_subscription_date", length = 19)
	public Date getLastSubscriptionDate() {
		return this.lastSubscriptionDate;
	}

	public void setLastSubscriptionDate(Date lastSubscriptionDate) {
		this.lastSubscriptionDate = lastSubscriptionDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_deactivation_date", length = 19)
	public Date getLastDeactivationDate() {
		return this.lastDeactivationDate;
	}

	public void setLastDeactivationDate(Date lastDeactivationDate) {
		this.lastDeactivationDate = lastDeactivationDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_billing_date", length = 19)
	public Date getLastBillingDate() {
		return this.lastBillingDate;
	}

	public void setLastBillingDate(Date lastBillingDate) {
		this.lastBillingDate = lastBillingDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_renewal_date", length = 19)
	public Date getLastRenewalDate() {
		return this.lastRenewalDate;
	}

	public void setLastRenewalDate(Date lastRenewalDate) {
		this.lastRenewalDate = lastRenewalDate;
	}

	@Column(name = "retry_number")
	public Integer getRetryNumber() {
		return this.retryNumber;
	}

	public void setRetryNumber(Integer retryNumber) {
		this.retryNumber = retryNumber;
	}

}
