package org.saxt.cms.model;
// Generated Mar 3, 2018 2:20:56 PM by Hibernate Tools 3.6.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Template generated by hbm2java
 */
@Entity
@Table(name = "template", catalog = "cms")
public class Template implements java.io.Serializable {

	private Integer id;
	private String name;
	private String description;
	private String type;
	private String htmlPreview;
	private String html;

	public Template() {
	}

	public Template(String name, String description, String type, String htmlPreview, String html) {
		this.name = name;
		this.description = description;
		this.type = type;
		this.htmlPreview = htmlPreview;
		this.html = html;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "type", length = 8)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "html_preview", length = 65535)
	public String getHtmlPreview() {
		return this.htmlPreview;
	}

	public void setHtmlPreview(String htmlPreview) {
		this.htmlPreview = htmlPreview;
	}

	@Column(name = "html", length = 65535)
	public String getHtml() {
		return this.html;
	}

	public void setHtml(String html) {
		this.html = html;
	}

}
